language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 5.3
          dist: precise
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
        # test 2.7 LTS
        - php: 5.6
          env: SYMFONY_VERSION='2.7.*'
        # test 2.8 LTS
        - php: 5.6
          env: SYMFONY_VERSION='2.8.*'
        # test the latest stable 3.x release
        - php: 5.6
          env: SYMFONY_VERSION=^3.0
        # test the latest release (including beta releases)
        - php: 7.1
          env: DEPENDENCIES=beta

before_install:
    - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit
